# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple CLI for task management"
  homepage "https://github.com/PriyabrataMo/tasks"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PriyabrataMo/tasks/releases/download/v1.0.0/tasks_1.0.0_darwin_amd64.tar.gz"
      sha256 "7ea7f1ef4b69ff4e9a541a97ff435f5f2016e4fd1d330b92fa08d1aab95bb532"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PriyabrataMo/tasks/releases/download/v1.0.0/tasks_1.0.0_darwin_arm64.tar.gz"
      sha256 "ac5723cb48e51c459a12b05f60c0be5d798d75e29573cd401e63baaa0aededa6"

      def install
        bin.install "tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PriyabrataMo/tasks/releases/download/v1.0.0/tasks_1.0.0_linux_amd64.tar.gz"
        sha256 "c0bedd0a5c213b15afa10d83976f5f7a70fdd63a5aac83eefbfbc350f4a2db2a"

        def install
          bin.install "tasks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PriyabrataMo/tasks/releases/download/v1.0.0/tasks_1.0.0_linux_arm64.tar.gz"
        sha256 "c5db7d67f31fdb0a9f2b56b2d3b5d8ffe43f39bd64125e8d28cafadde40c39c1"

        def install
          bin.install "tasks"
        end
      end
    end
  end
end
